### ISSUE TITLE
Maximum length for encoding/decoding

### ISSUE THREAD

**Issue by zongweil** [JonMcPherson/open-location-code#1]
Hello!

Would you mind adding an internal max length to your implementation, as per google/open-location-code#190?

Specifically, the following changes will be made:

- If you ask the library to encode a lat/long with more than 15 digits, the library will return a plus code with 15 digits.
- If you ask the library to decode a plus code with more than 15 digits, the library will only take the first 15 digits into account with the returned code area.
- Plus codes with more than 15 digits will be treated as valid if all the other validity constraints are satisfied. If the plus code has an invalid character after the 15th digit, it will be treated as invalid.

You can follow the example of the Java implementation here: https://github.com/google/open-location-code/pull/209

Let me know if you have time to do this in the next couple weeks.

**Comment by JonMcPherson** [comment]
Yea no problem. It is done.
https://github.com/JonMcPherson/open-location-code/pull/2

**Comment by zongweil** [comment]
Thanks!
