### ISSUE TITLE
Calling C# OpenLocationCode.Encode with length 2 fails 'Illegal code length 2'

### ISSUE THREAD

**Issue by brewmanz** [JonMcPherson/open-location-code#10]
Calling C# OpenLocationCode.Encode with length 2 fails with 'System.ArgumentException: Illegal code length 2.'.
I am using NuGet package OpenLocationCode by Jon McPherson, v2.1.0
This is for both GeoPoint and lat/long.
A length of 2 should be valid (https://github.com/google/open-location-code/blob/master/docs/specification.md) giving a 'box' 20 degrees across.
My test code is

        [TestMethod]
        public void UT_HD0099_Encode_LL()
        {
            string res;
            res = Google.OpenLocationCode.OpenLocationCode.Encode(12.123456789, 123.123456789, 11);
            Assert.AreEqual("7Q4544FF+99P", res);
            res = Google.OpenLocationCode.OpenLocationCode.Encode(12.123, 123.123, 4);
            Assert.AreEqual("7Q450000+", res);
            res = Google.OpenLocationCode.OpenLocationCode.Encode(12.123, 123.123, 2);
            Assert.AreEqual("7Q000000+", res);
        }

**Comment by brewmanz** [comment]
PR#11 created, also fixing multiple other test issues. e.g. allowing tests to run under either Linux or Windows, allowing encoding.csv to include failures as documented, checking failure of short odd lengths .

**Comment by JonMcPherson** [comment]
Thanks!
I commented on and merged PR https://github.com/JonMcPherson/open-location-code/pull/11
