### ISSUE TITLE
Using PlusCodes with Locality

### ISSUE THREAD

**Issue by Borriez** [JonMcPherson/open-location-code#12]
Is there a way to include the Locality with this solution.

The implementation works excellent with proper Plus Codes, ie: "5G3CQ877+X8", converts beautifully to a workable location.
However, when I try to process another Plus Code like this: "Q877+X8 Bethlehem" (Which translates to the same location), I receive an Exception Error, which I understand happens and why it happens.

How does one convert the "Bethlehem" to the pre-code of "5G3C" in this example?

Regards
Borriez

**Comment by JonMcPherson** [comment]
This library and all of the other implementations are just for encoding/decoding a full or short Open Location Code _offline_ and does not support geocoding named locations for the pre-code. I believe you would need to use some online service for that.
