### ISSUE TITLE
Underlying math: decimal or double?

### ISSUE THREAD

**Issue by epsitec** [JonMcPherson/open-location-code#5]
How should the coordinates be represented? Either stick to `decimal` or to `double`...

- The public API of `OpenLocationCode` is based on `double` for the coordinates, yet
  some computations are based on `decimal`.
- The `CodeArea` constructor expects `decimal` as its input arguments, yet all its properties
  are of type `double`.

As the precision of the encoded coordinates is limited, I don't feel that using the more
precise `decimal` representation useful in this library. I'd stick to `double`.

**Comment by JonMcPherson** [comment]
good point.  I used decimal since the Java implementation used BigDecimal, however the extra precision isn't necessary, and all of the tests pass when computing using double even for cases with high precision.

**Comment by JonMcPherson** [comment]
New algorithm doesn't do floating point arithmetic anymore
