### ISSUE TITLE
Floating point precision issues for C#

### ISSUE THREAD

**Issue by zongweil** [JonMcPherson/open-location-code#8]
Hello from the main Open Location Code repo!

We're currently working on fixing floating point precision issues with the various implementations (see [here](https://github.com/google/open-location-code/issues/307)). For the implementations not directly in the main repo, we're asking for the owners to update their code accordingly. Would you be able to do the following when you get a chance?

1) Run the new test cases in test_data/encoding.csv.
2) If they fail, fix your implementation to properly handle the floating point precision issues. I'll post again when we have a commit that you can use for reference.

**Comment by JonMcPherson** [comment]
👍 yea I'll update this project to address this issue within a week.

**Comment by JonMcPherson** [comment]
Finally got this merged in  PR https://github.com/JonMcPherson/open-location-code/pull/9.
Sorry for the delay.

Also FYI, I noticed this issue wasn't being tracked in https://github.com/google/open-location-code/projects/1
